default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: weatherchan-bot_development

test:
  <<: *default
  database: weatherchan-bot_test

production:
  <<: *default
  database: heroku_c8c5f1cef0aaf32
  username: be3bf202aafec2
  password: <%= ENV['DATABASE_PASSWORD'] %>
